import React from 'react';
import ReactDOM from 'react-dom';
import './pages/styles.css'; // Include your CSS here
import App from './App';
import {Amplify} from 'aws-amplify';
import awsconfig from './aws-exports'; // Ensure you have this file generated by Amplify CLI

Amplify.configure(awsconfig);

ReactDOM.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
  document.getElementById('root')
);
